- name: 'Deploy to Azure Web App'
  uses: azure/webapps-deploy@v3
  id: deploy-to-webapp
  with:
    app-name: 'syedstockmarket'
    slot-name: 'Production'
    publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FCA03FBFAE514B228A8498E2E5EA8964 }}
